# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USZEsP-cg2Wzfu0C1aEFE2rE8-Z5eP_A
"""

!mkdir modulo2_hashing

class AgendaDeContacto:
  def __init__(self):
    self.contacto_dict={}
  def add_contacto (self,nombre,numero):
    self.contacto_dict[nombre]=numero

  # Este método debe estar indentado dentro de la clase
  def buscar_contacto(self,nombre):
    numero=self.contacto_dict.get(nombre)
    if numero:
        return f"Encontrado El telefono de {nombre} es: {numero}"
    else:
        # 'name' se refiere a os.name si se importa. Debería ser 'nombre'
        return f"No se ha encontrado el contacto ´{nombre}´"

# Crear la agenda y probarla
mi_agenda = AgendaDeContacto()
mi_agenda.add_contacto("Ana", "555-1234")

# Probar la búsqueda
print(mi_agenda.buscar_contacto("Ana"))
print(mi_agenda.buscar_contacto("Carlos"))

# Commented out IPython magic to ensure Python compatibility.
# %%writefile modulo2_hashing/agenda_diccionarios.py
# class AgendaDeContacto:
#     def __init__(self):
#         self.contacto_dict = {}
# 
#     def add_contacto(self, nombre, numero):
#         if nombre in self.contacto_dict:
#             print(f"Advertencia: El contacto '{nombre}' ya existe.")
#         else:
#             self.contacto_dict[nombre] = numero
#             print(f"Contacto '{nombre}' guardado exitosamente.")
# 
#     def buscar_contacto(self, nombre):
#         numero = self.contacto_dict.get(nombre)
#         if numero:
#             return f"Encontrado! El teléfono de {nombre} es: {numero}"
#         else:
#             return f"No se ha encontrado el contacto '{nombre}'"
# 
# if __name__ == "__main__":
#     mi_agenda = AgendaDeContacto()
#     mi_agenda.add_contacto("Ana", "555-1234")
#     mi_agenda.add_contacto("Zulema", "555-9999")
# 
#     print(mi_agenda.buscar_contacto("Ana"))
#     print(mi_agenda.buscar_contacto("Carlos"))

!python modulo2_hashing/agenda_diccionarios.py

from google.colab import drive
drive.mount('/content/drive')